### ISSUE TITLE
mfrac image

### ISSUE THREAD

**Issue by esheldon** [lsst/cell_coadds#21]
I saw this in the image planes

https://github.com/lsst/cell_coadds/blob/88a373ac7738320530baad8b2eeedd49f9e93fcc/python/lsst/cell_coadds/_image_planes.py#L74

However we do not actually calculate that mapping

**Comment by esheldon** [comment]
We calculate an image where each pixel value is the fraction of images going into the coadd which were interpolated

**Comment by arunkannawadi** [comment]
Addressed in #20
